version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'suno-laravel'
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
  redis:
    container_name: suno_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    restart: always